---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	model(model)
	tools(tools)
	ModelCallLimitMiddleware\2ebefore_model(ModelCallLimitMiddleware.before_model)
	ModelCallLimitMiddleware\2eafter_model(ModelCallLimitMiddleware.after_model)
	ToolCallLimitMiddleware\2eafter_model(ToolCallLimitMiddleware.after_model)
	ToolCallLimitMiddleware\5bsql_db_query\5d\2eafter_model(ToolCallLimitMiddleware[sql_db_query].after_model)
	SummarizationMiddleware\2ebefore_model(SummarizationMiddleware.before_model)
	TodoListMiddleware\2eafter_model(TodoListMiddleware.after_model)
	__end__([<p>__end__</p>]):::last
	ModelCallLimitMiddleware\2eafter_model -.-> ModelCallLimitMiddleware\2ebefore_model;
	ModelCallLimitMiddleware\2eafter_model -.-> __end__;
	ModelCallLimitMiddleware\2eafter_model -.-> tools;
	ModelCallLimitMiddleware\2ebefore_model -.-> SummarizationMiddleware\2ebefore_model;
	ModelCallLimitMiddleware\2ebefore_model -.-> __end__;
	SummarizationMiddleware\2ebefore_model --> model;
	TodoListMiddleware\2eafter_model --> ToolCallLimitMiddleware\5bsql_db_query\5d\2eafter_model;
	ToolCallLimitMiddleware\2eafter_model -.-> ModelCallLimitMiddleware\2eafter_model;
	ToolCallLimitMiddleware\2eafter_model -.-> __end__;
	ToolCallLimitMiddleware\5bsql_db_query\5d\2eafter_model -.-> ToolCallLimitMiddleware\2eafter_model;
	ToolCallLimitMiddleware\5bsql_db_query\5d\2eafter_model -.-> __end__;
	__start__ --> ModelCallLimitMiddleware\2ebefore_model;
	model --> TodoListMiddleware\2eafter_model;
	tools -.-> ModelCallLimitMiddleware\2ebefore_model;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
